name: Run Tests and Lints 

  on:
    push:
      branches:
        - main

jobs:
  test_and_lint:
    runs-on: ubuntu-lates
    name: Run Jest tests and ESLint
    steps:
      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1

      - run: npm run lint (Run ESLint)

      - run: npm run test (Run Jest)
